languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Federico Izzo"
logo = ""
description = "Personal website"

dateFormat = "2 January 2006"

[author]
  name = "Federico Izzo"
  image = "me.jpg"
  headline = ""
  bio = ""
  links = [
    { email = "mailto:&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#104;&#105;&#64;&#102;&#101;&#100;&#101;&#105;&#122;&#122;&#111;&#46;&#100;&#101;&#118;" },
    { github = "https://github.com/fedeizzo" },
    { linkedin = "https://linkedin.com/in/fedeizzo" },
  ]
